paddle_ocr: null

landingai_ocr: 
  model: dpt-2-latest

protonx_legal_text_corrector:
    model_path: protonx-models/protonx-legal-tc
    tokenizer_config:
      return_tensors: "pt"
      truncation: true
      max_length: 512
    seq2seq_config:
        num_beams: 10
        num_return_sequences: 1     # <- return all beams
        max_new_tokens: 512
        early_stopping: true
        return_dict_in_generate: true  # <- return full dict
        output_scores: true