# Technical Parameters for DataJuicer Server

clean_content:
  remove_html: true
  remove_emojis: false
  text_column: "text"

refining_filter:
  min_len: 10
  max_len: 100000
  alphanumeric_ratio: 0.1
  text_column: "text"

language_id:
  expected_lang: "vi"
  min_score: 0.8
  text_column: "text"
